package com.lendagepocprojects.basicloanqualification.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LeadInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String state;
	private int eligibleDebt;
	private int fico;
	private int countHomesFinanced;
	private int totalMortgageLiability;
	private java.lang.String propertyType;

	private boolean qualified;

	private int propertyValue;

	private double cltv;

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public int getEligibleDebt() {
		return this.eligibleDebt;
	}

	public void setEligibleDebt(int eligibleDebt) {
		this.eligibleDebt = eligibleDebt;
	}

	public int getTotalMortgageLiability() {
		return this.totalMortgageLiability;
	}

	public void setTotalMortgageLiability(int totalMortgageLiability) {
		this.totalMortgageLiability = totalMortgageLiability;
	}

	public java.lang.String getPropertyType() {
		return this.propertyType;
	}

	public void setPropertyType(java.lang.String propertyType) {
		this.propertyType = propertyType;
	}

	public int getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(int propertyValue) {
		this.propertyValue = propertyValue;
	}

	public double getCltv() {
		return this.cltv;
	}

	public void setCltv(double cltv) {
		this.cltv = cltv;
	}

	public boolean isQualified() {
		return this.qualified;
	}

	public void setQualified(boolean qualified) {
		this.qualified = qualified;
	}

	public int getFico() {
		return this.fico;
	}

	public void setFICO(int fico) {
		this.fico = fico;
	}

	public int getCountHomesFinanced() {
		return this.countHomesFinanced;
	}

	public void setCountHomesFinanced(int countHomesFinanced) {
		this.countHomesFinanced = countHomesFinanced;
	}

	public LeadInformation() {
	}

	public LeadInformation(java.lang.String state, int eligibleDebt, int fico,
			int countHomesFinanced, int totalMortgageLiability,
			java.lang.String propertyType, boolean qualified,
			int propertyValue, double cltv) {
		this.state = state;
		this.eligibleDebt = eligibleDebt;
		this.fico = fico;
		this.countHomesFinanced = countHomesFinanced;
		this.totalMortgageLiability = totalMortgageLiability;
		this.propertyType = propertyType;
		this.qualified = qualified;
		this.propertyValue = propertyValue;
		this.cltv = cltv;
	}

}